### PR TITLE
Improve Pod accessibility on search page

### PR DESCRIPTION
**Pull request by Badatos**
+ add some "role="button" on some links
+ "local login" button has now secondary class
+ replace the "&times" in remove filter links by CSS
+ re-display labels in search form
+ rename "#mytabcontent" into "#video-meta", as it represents more its purpose
+ some code formatting on pod.css
+ some code formating in .py (add __author__ and __license__ pydoc)
+ Fix a small css bug by adding "col-md-9" in base.html to prevent aside behing diplayed on bottom of page when main content very large strings (like long URL)

### CODE REVIEW

**Review by ptitloup — COMMENTED** [review]
A tester mais ok pour moi !

**Review by ptitloup — APPROVED** [review]
Ok pour moi

**Review by JoshuaBaubry — APPROVED** [review]
C'est bon pour moi !

**Comment by ptitloup** [comment]
Merci @JoshuaBaubry

**Pull request merged**
