### PR TITLE
Dev #2.7.2

### PR DESCRIPTION
**Pull request by ptitloup**

### CODE REVIEW

**Comment by ptitloup** [comment]
- Improve accessiblity
- fix csrf in video_add
- Fix bug on editing video when comment is disabled
- bump deepspeech version to 0.9.1
- add building supervision in live
- improve Pod/BBB relation
- Use github action for unit-test
- Add field in recorder to improve treatment

**Comment by ptitloup** [comment]
- fix bugwith video playback rate
- improve css video
- delete old BBB meetings

**Comment by ptitloup** [comment]
- fixbug restricition video add for non staff if restrict active

**Comment by JoshuaBaubry** [comment]
Après quelques test des nouvelles fonctionnalités pour moi c'est ok !

**Comment by ptitloup** [comment]
Improve accessiblity
fix csrf in video_add
Fix bug on editing video when comment is disabled
bump deepspeech version to 0.9.1
add building supervision in live
improve Pod/BBB relation
Use github action for unit-test
Add field in recorder to improve treatment
fix bugwith video playback rate
improve css video
delete old BBB meetings
fixbug restricition video add for non staff if restrict active
Add my videos categories
Use thread to index video in ES
Use MODELTRANSLATION_FALLBACK_LANGUAGES setting

**Comment by ptitloup** [comment]
Improve and fix bug video stats | fix is video encoded property

**Pull request merged**
